In der unten stehenden Datentabelle sind die Kaltmiete, Wohnfläche und das Baujahr für fünf Wohnungen zusammengefasst. Die Werte dieser Tabelle werden in einem _ndarray_ _wohnungsdaten_ gespeichert.

<center>
<table>
  <tr>
    <th> <center></center> </th>
    <th> Kaltmiete in Euro </th>
    <th> Wohnfläche in qm</th>
    <th> Baujahr </th>
  </tr>
  <tr>
    <td> Wohnung 1 </td>
    <td> <center>649</center> </td>
    <td> <center>73</center> </td>
    <td> <center>1954</center> </td>
  </tr>
    <tr>
    <td> Wohnung 2 </td>
    <td> <center>1040</center> </td>
    <td> <center>83</center> </td>
    <td> <center>2022</center> </td>
  </tr>
    <tr>
    <td> Wohnung 3 </td>
    <td> <center>650</center> </td>
    <td> <center>65</center> </td>
    <td> <center>1954</center> </td>
  </tr>
    <tr>
    <td> Wohnung 4 </td>
    <td> <center>1040</center> </td>
    <td> <center>56</center> </td>
    <td> <center>1875</center> </td>
  </tr>
    <tr>
    <td> Wohnung 5 </td>
    <td> <center>858</center> </td>
    <td> <center>65</center> </td>
    <td> <center>2022</center> </td>
  </tr>
</table>
</center>

In [20]:
# Bitte den folgenden Programmcode vor Bearbeitung der Aufgaben ausführen

from scipy import stats
import numpy as np

# Wir legen die Werte der Datentabelle in einem ndarray ab.
wohnungsdaten = np.array([[649, 73, 1954], [1040, 83, 2022],
                          [650, 65, 1954], [1040, 56, 1875],
                          [858, 65, 2022]])

print(wohnungsdaten)

[[ 649   73 1954]
 [1040   83 2022]
 [ 650   65 1954]
 [1040   56 1875]
 [ 858   65 2022]]


# Aufgabe (_Minimalwert_)

Schreibe eine Anweisung, die den Minimalwert für jedes Merkmal der oberen Datentabelle berechnet. Dabei soll keine Untergrenze angegeben werden.

In [21]:
# Hier kommt deine Lösung
print(stats.tmin(wohnungsdaten, axis=0))  # Minimalwerte je Spalte


[ 649   56 1875]


# Aufgabe (_Maximalwert_)

Schreibe eine Anweisung, die den Maximalwert für jedes Merkmal der oberen Datentabelle berechnet.

In [22]:
# Hier kommt deine Lösung
print(stats.tmax(wohnungsdaten, axis=0))  # Maximalwerte je Spalte


[1040   83 2022]


# Aufgabe (_Modus_)

Schreibe eine Anweisung, die die Modi der Merkmale für die obere Datentabelle berechnet. Dabei sollen diese in einem eindimensionalen Array ausgegeben werden.

In [23]:
# Hier kommt deine Lösung
print(stats.mode(wohnungsdaten, axis=0))  # Modalwerte je Spalte


ModeResult(mode=array([1040,   65, 1954]), count=array([2, 2, 2]))


# Aufgabe (_Mittelwert_)

Schreibe eine Anweisung, die die Mittelwerte aller Merkmale der oberen Datentabelle berechnet.

In [24]:
# Hier kommt deine Lösung
print(stats.tmean(wohnungsdaten, axis=0))  # Mittelwerte je Spalte


[ 847.4   68.4 1965.4]


# Aufgabe (_Median_)

Schreibe eine Anweisung, die die Mediane aller Merkmale der oberen Datentabelle berechnet.

In [25]:
# Hier kommt deine Lösung
print(np.median(wohnungsdaten, axis=0))  # Medianwerte je Spalte


[ 858.   65. 1954.]
